fix(useContributorFilter): reset contributor on change tab
dis-moi/extension pull request #1143
Opened 2021-09-23 18:09 UTC by gregoirelacoste

closes #1141

2021-09-26 13:03 UTC, lutangar requested changes

2021-09-26 13:03 UTC, lutangar commented on src/app/profiles/hooks/useContributorsFilters.ts
> +    console.log(
We shouldn't log anything in the content script.
We may log things in the background using the appropriate `logger` service.

2021-09-27 07:12 UTC, JalilArfaoui approved these changes
Seems fine... Apart from the forgotten `console.logs`

2021-11-09 16:39 UTC, merged

2021-11-09 17:37 UTC, JalilArfaoui commented
:tada: This PR is included in version 3.91.1 :tada:

The release is available on [GitHub release](https://github.com/dis-moi/extension/releases/tag/v3.91.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: