doc(stores): document how to handle the Mozilla review process
dis-moi/extension pull request #756
Opened 2020-12-08 10:32 UTC by JalilArfaoui

2021-01-12 15:28 UTC, lutangar requested changes

2021-01-12 15:28 UTC, lutangar commented on docs/CONTRIBUTING.md
> +In order for the Mozilla review to complete successfully, please the following steps :
please the following steps -> please follow these steps
> or smthing like that

2021-01-12 15:28 UTC, lutangar commented on docs/CONTRIBUTING.md
> +- Create a `buildDisMoi.sh` file on your machine with the following content :
Could we ease the process and prepare at least part of this script ?
Maybe embed a part of it in the `package.json` or a dedicated script in `bin` dir.

2021-01-12 15:28 UTC, lutangar commented on docs/CONTRIBUTING.md
> +Note: We plan to remove any SendInBlue direct call from extension soon.
Good to know :D

Could you format it as a note please? 
> `>`

2021-01-12 15:44 UTC, lutangar commented
> This PR is the response to issue #743

2021-01-26 14:50 UTC, lutangar commented
ping @JalilArfaoui

2021-02-24 14:07 UTC, lutangar commented
@JalilArfaoui I'm going to take this back since *sendinblue* is going to be removed.
> see #161

However if we want to fully automate the build on Firefox there are still these issues which aren't resolved at __mozilla__:
This https://github.com/mozilla/addons-server/issues/9913 is blocking https://github.com/mozilla/sign-addon/issues/409 and thus blocking us.

2021-02-24 14:20 UTC, lutangar commented
@JalilArfaoui be re-reading your doc, I wonder if we can remove the docker requirement, I think I remember an issue with node version...

2021-02-24 14:30 UTC, lutangar commented
Also when trying to login as `infrastructure@lmem.net` to the **Firefox account** as mentionned in the doc I get the following error:
 ```
 Primary account email required for sign-in
 ```
 @MaartenLMEM @JalilArfaoui

2021-03-04 10:15 UTC, lutangar commented
I'm closing this in favor of #800

2021-03-08 22:14 UTC, JalilArfaoui commented
@lutangar It’s cool that we can get rid of the ugly `.sh` part … but I don’t get why this doc PR is moved into a backend PR about posting contributions ?

Let’s update this one instead, no ?

2021-03-09 07:43 UTC, lutangar commented
@JalilArfaoui sorry wrong issue

> see  #161

2021-03-24 17:04 UTC, christpet commented
@lutangar is this really in staging?

2021-03-25 08:04 UTC, lutangar commented
Superseded by #800

2021-03-25 08:04 UTC, closed without merging