English translation 1
dis-moi/extension pull request #853
Opened 2021-03-18 12:29 UTC by christpet

This is good to go!

2021-03-18 12:44 UTC, gregoirelacoste requested changes

2021-03-18 12:44 UTC, gregoirelacoste commented on src/i18n/resources/en/extension.json
> -    "medium": "Le {{date, DD/MM/YYYY}}"
We must remove the "Le"

2021-03-18 12:44 UTC, christpet commented on src/i18n/resources/en/extension.json
> -    "medium": "Le {{date, DD/MM/YYYY}}"
Ah good find ;)

2021-03-18 12:46 UTC, christpet commented on src/i18n/resources/en/extension.json
> +    "medium": "Le {{date, MM/DD/YYYY}}"
```suggestion
    "medium": "{{date, MM/DD/YYYY}}"
```

2021-03-18 13:33 UTC, merged

2021-03-19 06:40 UTC, bmenant commented
:tada: This PR is included in version 3.67.0 :tada:

The release is available on [GitHub release](https://github.com/dis-moi/extension/releases/tag/v3.67.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-03-22 09:04 UTC, lutangar commented
> https://github.com/dis-moi/extension/pull/854#issuecomment-803881548