English translation - profiles
dis-moi/extension pull request #854
Opened 2021-03-18 12:43 UTC by christpet

All set - the only thing I'm not sure about is the changed date format.

2021-03-18 12:48 UTC, gregoirelacoste requested changes
Nice, All that's missing is "all", thank you !!

2021-03-18 12:48 UTC, gregoirelacoste commented on src/i18n/resources/en/profiles.json
>      "all": "Tous"
it miss "all" ?

2021-03-18 12:48 UTC, gregoirelacoste commented on src/i18n/resources/en/profiles.json
> +    "since": "Since {{date, MM/DD/YYYY}}"
Fine !

2021-03-18 13:27 UTC, christpet commented on src/i18n/resources/en/profiles.json
>      "all": "Tous"
Ah yes I did!

2021-03-18 13:27 UTC, christpet commented on src/i18n/resources/en/profiles.json
>      "all": "Tous"
Thanks!

2021-03-18 13:28 UTC, christpet commented on src/i18n/resources/en/profiles.json
>      "all": "Tous"
```suggestion
    "all": "All"
```

2021-03-18 13:57 UTC, merged

2021-03-19 06:40 UTC, bmenant commented
:tada: This PR is included in version 3.67.0 :tada:

The release is available on [GitHub release](https://github.com/dis-moi/extension/releases/tag/v3.67.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-03-22 08:50 UTC, lutangar commented
@gregoirelacoste  you let unformatted commit messages slip through the pipeline.
I might add an "automated thing" to prevent this to happens unnoticed.

> For reference, this convention is responsible for setting  the extension version number and generates changelog on new releases:
> https://github.com/dis-moi/extension/releases
>
> This is mentionned here and there:
> https://github.com/dis-moi/extension/blob/master/docs/CONTRIBUTING.md#commits
> https://github.com/dis-moi/docs/pull/1/files

@christpet I'd be more confortable if a tech person would hit the merge button as long as we can let human errors go through to the pipe unnoticed.