feat(backgroundTranslation): serviceMessage
dis-moi/extension pull request #945
Opened 2021-05-04 08:02 UTC by gregoirelacoste

closes #909

2021-05-04 08:15 UTC, gregoirelacoste commented
@MaartenLMEM are you ok with this translation ? https://github.com/dis-moi/extension/pull/945/files#diff-7fb75433852be48976b2d6861e57933351a3f1f0344f291de0307c2f9d1c2479R137

2021-05-04 12:28 UTC, MaartenLMEM commented
will be reviewed during our next meeting with @prk-dismoi

2021-05-10 10:22 UTC, lutangar approved these changes
This is mostly wording and looks ok as far as I'm concerned, @MaartenLMEM I'll let you give the final word.

2021-05-10 10:33 UTC, MaartenLMEM requested changes

2021-05-10 10:33 UTC, MaartenLMEM commented on src/i18n/resources/en/extension.json
> +    "label": "Choose my sources",
Choose my contributors

2021-05-10 10:33 UTC, MaartenLMEM commented on src/i18n/resources/fr/extension.json
> +    "label": "Choisir mes sources",
Choisir mes contributeurs

2021-05-10 10:34 UTC, MaartenLMEM commented
just a little change in wording, all right to merge after

2021-05-11 07:50 UTC, MaartenLMEM approved these changes

2021-05-11 07:51 UTC, merged