fix(youtubeVideoMessage): use notice state to memoize formated message
dis-moi/extension pull request #974
Opened 2021-05-13 16:19 UTC by gregoirelacoste

closes #969

2021-05-17 08:44 UTC, JalilArfaoui reviewed
Can you please explain what was the problem ? What was happening ?

2021-05-19 08:04 UTC, gregoirelacoste commented on src/app/lmem/format/message.ts
> +  return getMessageWithMediaPlayer(message);
this function is now useless, you're right

2021-05-31 09:03 UTC, lutangar commented
This need a rebase and a question is still unanswered.

2021-05-31 09:30 UTC, gregoirelacoste commented
the issue : https://github.com/dis-moi/extension/issues/969
in summary : `getMessageWithMediaPlayer()` in render return null when we change tab a second time. So to avoid that I put `getMessageWithMediaPlayer` in component did mount and set state with the result

2021-05-31 13:23 UTC, lutangar requested changes
I first intended to accept this PR but a few thing bothering me...
`formatMessage` function should be kept, not sure I understand the memo issue, but if you add the message to the state, you only need to edit the `NoticeDetails.tsx`, all the other updates bring more confusion to the codebase imho.

2021-05-31 13:53 UTC, merged

2021-05-31 13:56 UTC, gregoirelacoste commented
> `formatMessage`

this function do nothing anymore

2021-05-31 14:25 UTC, bmenant commented
:tada: This PR is included in version 3.76.4 :tada:

The release is available on [GitHub release](https://github.com/dis-moi/extension/releases/tag/v3.76.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: